Updated Results btn
ghulamyazdani/TruHealth pull request #88
Opened 2021-12-26 04:50 UTC by SachinMittal1766

@ghulamyazdani I have updated the CSS of results btn and now it is looking nice.

2021-12-26 17:23 UTC, ghulamyazdani requested changes

2021-12-26 17:23 UTC, ghulamyazdani commented on Assets/Css/style.css
> -.options{
Please revert these deletion of CSS as they are supposed to be there.bcz of this CSS of the button in Get help section is effected

2021-12-27 05:50 UTC, SachinMittal1766 commented
@ghulamyazdani I have made the needful changes

2021-12-28 05:12 UTC, ghulamyazdani approved these changes
LGTM 🥳 thanks for your valuable contribution

2021-12-28 05:12 UTC, merged